# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-snowflake-account
  description: "This component sets up the requirements for all other Snowflake components, including creating the Terraform service user"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







